export const departments = [
    {
        name: "Engineering",
        director: "John Doe",
        teams: 5,
        projects: 8,
        employeesCount: 50,
    },
    {
        name: "Marketing",
        director: "Jane Smith",
        teams: 3,
        projects: 4,
        employeesCount: 30,
    },
    {
        name: "Human Resources",
        director: "Alice Johnson",
        teams: 2,
        projects: 2,
        employeesCount: 20,
    },
    {
        name: "Sales",
        director: "Bob Brown",
        teams: 4,
        projects: 6,
        employeesCount: 40,
    },
    {
        name: "Finance",
        director: "Sarah Lee",
        teams: 3,
        projects: 5,
        employeesCount: 25,
    },
    {
        name: "Customer Support",
        director: "Chris Harris",
        teams: 3,
        projects: 4,
        employeesCount: 35,
    },
    {
        name: "Operations",
        director: "Diana Evans",
        teams: 4,
        projects: 7,
        employeesCount: 45,
    },
    {
        name: "Research",
        director: "Fiona Green",
        teams: 2,
        projects: 3,
        employeesCount: 15,
    },
    {
        name: "Legal",
        director: "George Harris",
        teams: 1,
        projects: 2,
        employeesCount: 10,
    },
    {
        name: "Administration",
        director: "Hannah Jackson",
        teams: 1,
        projects: 1,
        employeesCount: 8,
    },
];