export const employees = [
    {
        name: "Alex Johnson",
        position: "Software Engineer",
        department: "Engineering",
        status: "Active",
        teamName: "Alpha1",
    },
    {
        name: "Sophia Brown",
        position: "Product Manager",
        department: "Product",
        status: "On Leave",
        teamName: "Alpha2",
    },
    {
        name: "Liam Davis",
        position: "Designer",
        department: "Design",
        status: "Active",
        teamName: "Beta1",
    },
    {
        name: "Emma Wilson",
        position: "QA Engineer",
        department: "Quality Assurance",
        status: "Inactive",
        teamName: "Beta2",
    },
    {
        name: "Olivia Taylor",
        position: "HR Manager",
        department: "Human Resources",
        status: "Active",
        teamName: "Gamma1",
    },
    {
        name: "James Anderson",
        position: "Marketing Specialist",
        department: "Marketing",
        status: "Active",
        teamName: "Gamma2",
    },
    {
        name: "Michael Scott",
        position: "Data Analyst",
        department: "Data",
        status: "Active",
        teamName: "Delta1",
    },
    {
        name: "Ava Martinez",
        position: "DevOps Engineer",
        department: "Operations",
        status: "Inactive",
        teamName: "Delta2",
    },
    {
        name: "William Clark",
        position: "Business Analyst",
        department: "Business",
        status: "Active",
        teamName: "Epsilon1",
    },
    {
        name: "Isabella Moore",
        position: "Project Manager",
        department: "Project Management",
        status: "Active",
        teamName: "Epsilon2",
    },
];
