export const employees = [
    {
        name: "Person 1",
        position: "Software Engineer",
        department: "Engineering",
        status: "Active",
        teamName: "Alpha1",
    },
    {
        name: "Person 2",
        position: "Product Manager",
        department: "Product",
        status: "On Leave",
        teamName: "Alpha2",
    },
    {
        name: "Person 3",
        position: "Designer",
        department: "Design",
        status: "Active",
        teamName: "Beta1",
    },
    {
        name: "Person 4",
        position: "QA Engineer",
        department: "Quality Assurance",
        status: "Inactive",
        teamName: "Beta2",
    },
    {
        name: "Person 5",
        position: "HR Manager",
        department: "Human Resources",
        status: "Active",
        teamName: "Gamma1",
    },
    {
        name: "Person 6",
        position: "Marketing Specialist",
        department: "Marketing",
        status: "Active",
        teamName: "Gamma2",
    },
    {
        name: "Person 7",
        position: "Data Analyst",
        department: "Data",
        status: "Active",
        teamName: "Delta1",
    },
    {
        name: "Person 8",
        position: "DevOps Engineer",
        department: "Operations",
        status: "Inactive",
        teamName: "Delta2",
    },
    {
        name: "Person 9",
        position: "Business Analyst",
        department: "Business",
        status: "Active",
        teamName: "Epsilon1",
    },
    {
        name: "Person 10",
        position: "Project Manager",
        department: "Project Management",
        status: "Active",
        teamName: "Epsilon2",
    },
];