export const projects = [
    {
        name: "Project Alpha",
        department: "IT",
        manager: "John Doe",
        startDate: "2023-01-01",
        endDate: "2023-06-30",
        status: "Active",
        description: "Description for Project Alpha",
    },
    {
        name: "Project Beta",
        department: "HR",
        manager: "Jane Smith",
        startDate: "2023-02-01",
        endDate: "2023-07-31",
        status: "Completed",
        description: "Description for Project Beta",
    },
    {
        name: "Project Gamma",
        department: "Finance",
        manager: "Alice Johnson",
        startDate: "2023-03-01",
        endDate: "2023-08-31",
        status: "On Hold",
        description: "Description for Project Gamma",
    },
    {
        name: "Project Delta",
        department: "Marketing",
        manager: "Bob Brown",
        startDate: "2023-04-01",
        endDate: "2023-09-30",
        status: "Active",
        description: "Description for Project Delta",
    },
    {
        name: "Project Epsilon",
        department: "IT",
        manager: "Charlie Davis",
        startDate: "2023-05-01",
        endDate: "2023-10-31",
        status: "Cancelled",
        description: "Description for Project Epsilon",
    },
    {
        name: "Project Zeta",
        department: "HR",
        manager: "Diana Evans",
        startDate: "2023-06-01",
        endDate: "2023-11-30",
        status: "Postponed",
        description: "Description for Project Zeta",
    },
    {
        name: "Project Eta",
        department: "Finance",
        manager: "Ethan Foster",
        startDate: "2023-07-01",
        endDate: "2023-12-31",
        status: "Active",
        description: "Description for Project Eta",
    },
    {
        name: "Project Theta",
        department: "Marketing",
        manager: "Fiona Green",
        startDate: "2023-08-01",
        endDate: "2024-01-31",
        status: "Completed",
        description: "Description for Project Theta",
    },
    {
        name: "Project Iota",
        department: "IT",
        manager: "George Harris",
        startDate: "2023-09-01",
        endDate: "2024-02-29",
        status: "On Hold",
        description: "Description for Project Iota",
    },
    {
        name: "Project Kappa",
        department: "HR",
        manager: "Hannah Jackson",
        startDate: "2023-10-01",
        endDate: "2024-03-31",
        status: "Active",
        description: "Description for Project Kappa",
    },
];