export const teams = [
  {
    name: "Alpha1",
    project: "Project Alpha",
    leader: "John Doe",
    members: 5,
    department: "IT",
  },
  {
    name: "Alpha2",
    project: "Project Alpha",
    leader: "John Doe",
    members: 5,
    department: "IT",
  },
  {
    name: "Beta1",
    project: "Project Beta",
    leader: "Jane Smith",
    members: 3,
    department: "HR",
  },
  {
    name: "Beta2",
    project: "Project Beta",
    leader: "Jane Smith",
    members: 3,
    department: "HR",
  },
  {
    name: "Gamma1",
    project: "Project Gamma",
    leader: "Alice Johnson",
    members: 4,
    department: "Finance",
  },
  {
    name: "Gamma2",
    project: "Project Gamma",
    leader: "Alice Johnson",
    members: 4,
    department: "Finance",
  },
  {
    name: "Delta1",
    project: "Project Delta",
    leader: "Bob Brown",
    members: 6,
    department: "Marketing",
  },
  {
    name: "Delta2",
    project: "Project Delta",
    leader: "Bob Brown",
    members: 6,
    department: "Marketing",
  },
  {
    name: "Epsilon1",
    project: "Project Epsilon",
    leader: "Charlie Davis",
    members: 7,
    department: "IT",
  },
  {
    name: "Epsilon2",
    project: "Project Epsilon",
    leader: "Charlie Davis",
    members: 7,
    department: "IT",
  },
];
